version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dailywork_app
    ports:
      - "9092:9090"  # Host:Container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dailywork  # Corrected port
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Anish234
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"  # Host:Container
    environment:
      MYSQL_ROOT_PASSWORD: Anish234
      MYSQL_DATABASE: dailywork
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"  # Host:Container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_data:
